vich_uploader:
    db_driver: orm
    metadata:    #dans la vidéo, a checker selon la version, decommenter les trois dernieres lignes si besoin
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: /images/recette
            upload_destination: '%kernel.project_dir%/public/images/recette'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            #inject_on_load: false
            #delete_on_update: true
            #delete_on_remove: true